package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGAsteroidalChemical;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Acidic Asteroid"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGAcidicAsteroid extends SWGAsteroidalChemical {

  private static final long serialVersionUID = 6048867L;

  private static final int[] minStats = {0, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0};
  private static final int[] maxStats = {0, 0, 0, 0, 0, 0, 0, 1000, 0, 0, 0};

  private static final SWGAcidicAsteroid INSTANCE = new SWGAcidicAsteroid();

  SWGAcidicAsteroid() { super(); }

  public static SWGAcidicAsteroid getInstance() { return INSTANCE; }

  public int expectedStats() { return 1; }
  public int sortIndex() { return 801; }
  public int rcID() { return 764; }
  public String rcName() { return "Acidic Asteroid";}
  public String rcToken() { return "acid";}
  public boolean isSpaceOrRecycled()  { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
