package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGCarbonateOre;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Alantium Carbonate Ore"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGAlantiumCarbonateOre extends SWGCarbonateOre {

  private static final long serialVersionUID = 2079553L;

  private static final int[] minStats = {0, 300, 1, 0, 0, 400, 300, 1, 0, 1, 200};
  private static final int[] maxStats = {0, 414, 115, 0, 0, 498, 414, 1000, 0, 115, 330};

  private static final SWGAlantiumCarbonateOre INSTANCE = new SWGAlantiumCarbonateOre();

  SWGAlantiumCarbonateOre() { super(); }

  public static SWGAlantiumCarbonateOre getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 726; }
  public int rcID() { return 262; }
  public String rcName() { return "Alantium Carbonate Ore";}
  public String rcToken() { return "alcrb";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
