package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGCrystallineGemstone;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Byrothsis Crystalline Gemstone"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGByrothsisCrystallineGemstone extends SWGCrystallineGemstone {

  private static final long serialVersionUID = 1178155L;

  private static final int[] minStats = {0, 1, 1, 500, 0, 700, 1, 1, 0, 300, 300};
  private static final int[] maxStats = {0, 163, 163, 581, 0, 749, 66, 1000, 0, 414, 414};

  private static final SWGByrothsisCrystallineGemstone INSTANCE = new SWGByrothsisCrystallineGemstone();

  SWGByrothsisCrystallineGemstone() { super(); }

  public static SWGByrothsisCrystallineGemstone getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 760; }
  public int rcID() { return 148; }
  public String rcName() { return "Byrothsis Crystalline Gemstone";}
  public String rcToken() { return "bycry";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
