package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGIron;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Bronzium Iron"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGBronziumIron extends SWGIron {

  private static final long serialVersionUID = 2142809L;

  private static final int[] minStats = {169, 271, 536, 0, 0, 669, 203, 1, 0, 603, 603};
  private static final int[] maxStats = {269, 430, 676, 0, 0, 769, 323, 1000, 0, 723, 723};

  private static final SWGBronziumIron INSTANCE = new SWGBronziumIron();

  SWGBronziumIron() { super(); }

  public static SWGBronziumIron getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 663; }
  public int rcID() { return 270; }
  public String rcName() { return "Bronzium Iron";}
  public String rcToken() { return "brirn";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
