package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGExtrusiveOre;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Chronamite Extrusive Ore"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGChronamiteExtrusiveOre extends SWGExtrusiveOre {

  private static final long serialVersionUID = 2000483L;

  private static final int[] minStats = {0, 256, 349, 0, 0, 442, 43, 1, 0, 442, 442};
  private static final int[] maxStats = {0, 384, 461, 0, 0, 538, 139, 1000, 0, 538, 538};

  private static final SWGChronamiteExtrusiveOre INSTANCE = new SWGChronamiteExtrusiveOre();

  SWGChronamiteExtrusiveOre() { super(); }

  public static SWGChronamiteExtrusiveOre getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 701; }
  public int rcID() { return 252; }
  public String rcName() { return "Chronamite Extrusive Ore";}
  public String rcToken() { return "chext";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
