package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Chemical"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public class SWGChemical extends SWGInorganic {

  private static final long serialVersionUID = 55361L;

  private static final int[] minStats = {0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1};
  private static final int[] maxStats = {0, 0, 1000, 0, 0, 0, 1000, 1000, 1000, 1000, 1000};

  private static final SWGChemical INSTANCE = new SWGChemical();

  SWGChemical() { super(); }

  public static SWGChemical getInstance() { return INSTANCE; }

  public int expectedStats() { return 6; }
  public int sortIndex() { return 569; }
  public int rcID() { return 6; }
  public String rcName() { return "Chemical";}
  public String rcToken() { return "chm";}
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
