package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Class 5 Liquid Petro Fuel"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGClass5LiquidPetroFuel extends SWGKnownLiquidPetrochemFuel {

  private static final long serialVersionUID = 5993518L;

  private static final int[] minStats = {0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0};
  private static final int[] maxStats = {0, 0, 600, 0, 0, 0, 0, 1000, 1000, 0, 0};

  private static final SWGClass5LiquidPetroFuel INSTANCE = new SWGClass5LiquidPetroFuel();

  SWGClass5LiquidPetroFuel() { super(); }

  public static SWGClass5LiquidPetroFuel getInstance() { return INSTANCE; }

  public int expectedStats() { return 3; }
  public int sortIndex() { return 578; }
  public int rcID() { return 757; }
  public String rcName() { return "Class 5 Liquid Petro Fuel";}
  public String rcToken() { return "c5kpf";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
