package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGCopper;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Codoan Copper"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGCodoanCopper extends SWGCopper {

  private static final long serialVersionUID = 2356298L;

  private static final int[] minStats = {650, 241, 211, 0, 0, 335, 650, 1, 0, 450, 450};
  private static final int[] maxStats = {739, 383, 335, 0, 0, 415, 739, 1000, 0, 539, 539};

  private static final SWGCodoanCopper INSTANCE = new SWGCodoanCopper();

  SWGCodoanCopper() { super(); }

  public static SWGCodoanCopper getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 687; }
  public int rcID() { return 297; }
  public String rcName() { return "Codoan Copper";}
  public String rcToken() { return "cocpr";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
