package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Chanlon Intrusive Ore"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGChanlonIntrusiveOre extends SWGIntrusiveOre {

  private static final long serialVersionUID = 2055832L;

  private static final int[] minStats = {0, 262, 354, 0, 0, 723, 48, 1, 0, 539, 447};
  private static final int[] maxStats = {0, 404, 479, 0, 0, 777, 154, 1000, 0, 628, 553};

  private static final SWGChanlonIntrusiveOre INSTANCE = new SWGChanlonIntrusiveOre();

  SWGChanlonIntrusiveOre() { super(); }

  public static SWGChanlonIntrusiveOre getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 713; }
  public int rcID() { return 259; }
  public String rcName() { return "Chanlon Intrusive Ore";}
  public String rcToken() { return "chint";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
