package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGSiliclasticOre;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Cortosis Siliclastic Ore"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGCortosisSiliclasticOre extends SWGSiliclasticOre {

  private static final long serialVersionUID = 5092120L;

  private static final int[] minStats = {0, 382, 83, 0, 0, 382, 382, 1, 0, 71, 83};
  private static final int[] maxStats = {0, 568, 269, 0, 0, 568, 568, 1000, 0, 231, 269};

  private static final SWGCortosisSiliclasticOre INSTANCE = new SWGCortosisSiliclasticOre();

  SWGCortosisSiliclasticOre() { super(); }

  public static SWGCortosisSiliclasticOre getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 737; }
  public int rcID() { return 643; }
  public String rcName() { return "Cortosis Siliclastic Ore";}
  public String rcToken() { return "cosil";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
