package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Combined Radioactive Isotopes"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGCombinedRadioactiveIsotopes extends SWGRadioactive {

  private static final long serialVersionUID = 6547008L;

  private static final int[] minStats = {0, 0, 200, 0, 0, 0, 0, 200, 200, 0, 0};
  private static final int[] maxStats = {0, 0, 200, 0, 0, 0, 0, 200, 200, 0, 0};

  private static final SWGCombinedRadioactiveIsotopes INSTANCE = new SWGCombinedRadioactiveIsotopes();

  SWGCombinedRadioactiveIsotopes() { super(); }

  public static SWGCombinedRadioactiveIsotopes getInstance() { return INSTANCE; }

  public int expectedStats() { return 3; }
  public int sortIndex() { return 627; }
  public int rcID() { return 827; }
  public String rcName() { return "Combined Radioactive Isotopes";}
  public String rcToken() { return "crad";}
  public boolean isSpaceOrRecycled()  { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
