package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Colat Iron"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGColatIron extends SWGIron {

  private static final long serialVersionUID = 2150716L;

  private static final int[] minStats = {232, 371, 624, 0, 0, 731, 278, 1, 0, 678, 678};
  private static final int[] maxStats = {332, 530, 764, 0, 0, 831, 398, 1000, 0, 798, 798};

  private static final SWGColatIron INSTANCE = new SWGColatIron();

  SWGColatIron() { super(); }

  public static SWGColatIron getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 664; }
  public int rcID() { return 271; }
  public String rcName() { return "Colat Iron";}
  public String rcToken() { return "coirn";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
