package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGIron;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Dolovite Iron"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGDoloviteIron extends SWGIron {

  private static final long serialVersionUID = 2158623L;

  private static final int[] minStats = {294, 470, 711, 0, 0, 794, 353, 1, 0, 753, 753};
  private static final int[] maxStats = {394, 630, 851, 0, 0, 894, 473, 1000, 0, 873, 873};

  private static final SWGDoloviteIron INSTANCE = new SWGDoloviteIron();

  SWGDoloviteIron() { super(); }

  public static SWGDoloviteIron getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 665; }
  public int rcID() { return 272; }
  public String rcName() { return "Dolovite Iron";}
  public String rcToken() { return "dvirn";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
