package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGAluminum;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Duralumin Aluminum"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGDuraluminAluminum extends SWGAluminum {

  private static final long serialVersionUID = 2308856L;

  private static final int[] minStats = {525, 361, 361, 0, 0, 470, 615, 1, 0, 570, 570};
  private static final int[] maxStats = {658, 574, 574, 0, 0, 630, 802, 1000, 0, 730, 730};

  private static final SWGDuraluminAluminum INSTANCE = new SWGDuraluminAluminum();

  SWGDuraluminAluminum() { super(); }

  public static SWGDuraluminAluminum getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 677; }
  public int rcID() { return 291; }
  public String rcName() { return "Duralumin Aluminum";}
  public String rcToken() { return "dualu";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
