package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGSteel;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Duralloy Steel"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGDuralloySteel extends SWGSteel {

  private static final long serialVersionUID = 2237693L;

  private static final int[] minStats = {566, 696, 935, 0, 0, 948, 348, 1, 0, 935, 922};
  private static final int[] maxStats = {650, 800, 1000, 0, 0, 1000, 400, 1000, 0, 1000, 1000};

  private static final SWGDuralloySteel INSTANCE = new SWGDuralloySteel();

  SWGDuralloySteel() { super(); }

  public static SWGDuralloySteel getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 656; }
  public int rcID() { return 282; }
  public String rcName() { return "Duralloy Steel";}
  public String rcToken() { return "dlstl";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
