package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGGeothermalEnergy;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Endorian Geothermal Renewable Energy"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGEndorianGeothermalRenewableEnergy extends SWGGeothermalEnergy {

  private static final long serialVersionUID = 6159565L;

  private static final int[] minStats = {0, 0, 0, 0, 0, 0, 0, 500, 200, 0, 0};
  private static final int[] maxStats = {0, 0, 0, 0, 0, 0, 0, 1000, 1000, 0, 0};

  private static final SWGEndorianGeothermalRenewableEnergy INSTANCE = new SWGEndorianGeothermalRenewableEnergy();

  SWGEndorianGeothermalRenewableEnergy() { super(); }

  public static SWGEndorianGeothermalRenewableEnergy getInstance() { return INSTANCE; }

  public int expectedStats() { return 2; }
  public int sortIndex() { return 36; }
  public int rcID() { return 778; }
  public String rcName() { return "Endorian Geothermal Renewable Energy";}
  public String rcToken() { return "engeg";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
