package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Geothermal Energy"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public class SWGGeothermalEnergy extends SWGSiteRestrictedRenewableEnergy {

  private static final long serialVersionUID = 6127937L;

  private static final int[] minStats = {0, 0, 0, 0, 0, 0, 0, 200, 200, 0, 0};
  private static final int[] maxStats = {0, 0, 0, 0, 0, 0, 0, 1000, 1000, 0, 0};

  private static final SWGGeothermalEnergy INSTANCE = new SWGGeothermalEnergy();

  SWGGeothermalEnergy() { super(); }

  public static SWGGeothermalEnergy getInstance() { return INSTANCE; }

  public int expectedStats() { return 2; }
  public int sortIndex() { return 31; }
  public int rcID() { return 774; }
  public String rcName() { return "Geothermal Energy";}
  public String rcToken() { return "geg";}
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
