package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Gallinorian Rainbow Gem Crystalline Gemstone"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGGallinorianRainbowGemCrystallineGemstone extends SWGCrystallineGemstone {

  private static final long serialVersionUID = 1186062L;

  private static final int[] minStats = {0, 88, 88, 544, 0, 726, 36, 1, 0, 361, 361};
  private static final int[] maxStats = {0, 288, 288, 644, 0, 786, 116, 1000, 0, 501, 501};

  private static final SWGGallinorianRainbowGemCrystallineGemstone INSTANCE = new SWGGallinorianRainbowGemCrystallineGemstone();

  SWGGallinorianRainbowGemCrystallineGemstone() { super(); }

  public static SWGGallinorianRainbowGemCrystallineGemstone getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 761; }
  public int rcID() { return 149; }
  public String rcName() { return "Gallinorian Rainbow Gem Crystalline Gemstone";}
  public String rcToken() { return "gacry";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
