package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGHorn;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Ground Horn"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGGroundHorn extends SWGHorn {

  private static final long serialVersionUID = 6570729L;

  private static final int[] minStats = {0, 0, 200, 0, 0, 0, 200, 200, 0, 200, 200};
  private static final int[] maxStats = {0, 0, 200, 0, 0, 0, 200, 200, 0, 200, 200};

  private static final SWGGroundHorn INSTANCE = new SWGGroundHorn();

  SWGGroundHorn() { super(); }

  public static SWGGroundHorn getInstance() { return INSTANCE; }

  public int expectedStats() { return 5; }
  public int sortIndex() { return 251; }
  public int rcID() { return 830; }
  public String rcName() { return "Ground Horn";}
  public String rcToken() { return "ghrn";}
  public boolean isSpaceOrRecycled()  { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
