package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Inorganic"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public class SWGInorganic extends SWGResourceClass {

  private static final long serialVersionUID = 23733L;

  private static final int[] minStats = {1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1};
  private static final int[] maxStats = {1000, 1000, 1000, 1000, 0, 1000, 1000, 1000, 1000, 1000, 1000};

  private static final SWGInorganic INSTANCE = new SWGInorganic();

  SWGInorganic() { super(); }

  public static SWGInorganic getInstance() { return INSTANCE; }

  public int expectedStats() { return 10; }
  public int sortIndex() { return 568; }
  public int rcID() { return 2; }
  public String rcName() { return "Inorganic";}
  public String rcToken() { return "ino";}
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
