package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGIntrusiveOre;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Katrium Intrusive Ore"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGKatriumIntrusiveOre extends SWGIntrusiveOre {

  private static final long serialVersionUID = 5013050L;

  private static final int[] minStats = {0, 884, 899, 0, 0, 957, 513, 1, 0, 928, 913};
  private static final int[] maxStats = {0, 1000, 1000, 0, 0, 1000, 600, 1000, 0, 1000, 1000};

  private static final SWGKatriumIntrusiveOre INSTANCE = new SWGKatriumIntrusiveOre();

  SWGKatriumIntrusiveOre() { super(); }

  public static SWGKatriumIntrusiveOre getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 720; }
  public int rcID() { return 633; }
  public String rcName() { return "Katrium Intrusive Ore";}
  public String rcToken() { return "kaint";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
