package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGExtrusiveOre;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Kalonterium Extrusive Ore"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGKalonteriumExtrusiveOre extends SWGExtrusiveOre {

  private static final long serialVersionUID = 5613982L;

  private static final int[] minStats = {0, 416, 489, 0, 0, 562, 163, 1, 0, 562, 562};
  private static final int[] maxStats = {0, 544, 601, 0, 0, 658, 259, 1000, 0, 658, 658};

  private static final SWGKalonteriumExtrusiveOre INSTANCE = new SWGKalonteriumExtrusiveOre();

  SWGKalonteriumExtrusiveOre() { super(); }

  public static SWGKalonteriumExtrusiveOre getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 703; }
  public int rcID() { return 709; }
  public String rcName() { return "Kalonterium Extrusive Ore";}
  public String rcToken() { return "kaext";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
