package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Kashyyykian Avian Bones"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGKashyyykianAvianBones extends SWGAvianBone {

  private static final long serialVersionUID = 5661424L;

  private static final int[] minStats = {0, 0, 1, 0, 0, 0, 1, 1, 0, 100, 1};
  private static final int[] maxStats = {0, 0, 700, 0, 0, 0, 600, 1000, 0, 500, 500};

  private static final SWGKashyyykianAvianBones INSTANCE = new SWGKashyyykianAvianBones();

  SWGKashyyykianAvianBones() { super(); }

  public static SWGKashyyykianAvianBones getInstance() { return INSTANCE; }

  public int expectedStats() { return 5; }
  public int sortIndex() { return 248; }
  public int rcID() { return 715; }
  public String rcName() { return "Kashyyykian Avian Bones";}
  public String rcToken() { return "kavbn";}
  public boolean isHarvested() { return true; }
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
