package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Kammris Iron"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGKammrisIron extends SWGIron {

  private static final long serialVersionUID = 2174437L;

  private static final int[] minStats = {419, 670, 886, 0, 0, 919, 503, 1, 0, 903, 903};
  private static final int[] maxStats = {500, 800, 1000, 0, 0, 1000, 600, 1000, 0, 1000, 1000};

  private static final SWGKammrisIron INSTANCE = new SWGKammrisIron();

  SWGKammrisIron() { super(); }

  public static SWGKammrisIron getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 667; }
  public int rcID() { return 274; }
  public String rcName() { return "Kammris Iron";}
  public String rcToken() { return "kairn";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
