package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGExtrusiveOre;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Lidium Extrusive Ore"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGLidiumExtrusiveOre extends SWGExtrusiveOre {

  private static final long serialVersionUID = 2016297L;

  private static final int[] minStats = {0, 576, 629, 0, 0, 682, 283, 1, 0, 682, 682};
  private static final int[] maxStats = {0, 704, 741, 0, 0, 778, 378, 1000, 0, 778, 778};

  private static final SWGLidiumExtrusiveOre INSTANCE = new SWGLidiumExtrusiveOre();

  SWGLidiumExtrusiveOre() { super(); }

  public static SWGLidiumExtrusiveOre getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 705; }
  public int rcID() { return 254; }
  public String rcName() { return "Lidium Extrusive Ore";}
  public String rcToken() { return "liext";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
