package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGCrystallineGemstone;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Laboi Mineral Crystal Crystalline Gemstone"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGLaboiMineralCrystalCrystallineGemstone extends SWGCrystallineGemstone {

  private static final long serialVersionUID = 1209783L;

  private static final int[] minStats = {0, 713, 713, 856, 0, 914, 285, 1, 0, 799, 799};
  private static final int[] maxStats = {0, 913, 913, 956, 0, 974, 365, 1000, 0, 939, 939};

  private static final SWGLaboiMineralCrystalCrystallineGemstone INSTANCE = new SWGLaboiMineralCrystalCrystallineGemstone();

  SWGLaboiMineralCrystalCrystallineGemstone() { super(); }

  public static SWGLaboiMineralCrystalCrystallineGemstone getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 766; }
  public int rcID() { return 152; }
  public String rcName() { return "Laboi Mineral Crystal Crystalline Gemstone";}
  public String rcToken() { return "lacry";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
