package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGKnownReactiveGas;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Methane Reactive Gas"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGMethaneReactiveGas extends SWGKnownReactiveGas {

  private static final long serialVersionUID = 1083271L;

  private static final int[] minStats = {0, 0, 200, 0, 0, 0, 0, 1, 0, 0, 0};
  private static final int[] maxStats = {0, 0, 700, 0, 0, 0, 0, 1000, 0, 0, 0};

  private static final SWGMethaneReactiveGas INSTANCE = new SWGMethaneReactiveGas();

  SWGMethaneReactiveGas() { super(); }

  public static SWGMethaneReactiveGas getInstance() { return INSTANCE; }

  public int expectedStats() { return 2; }
  public int sortIndex() { return 776; }
  public int rcID() { return 136; }
  public String rcName() { return "Methane Reactive Gas";}
  public String rcToken() { return "mektv";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
