package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Malab Siliclastic Ore"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGMalabSiliclasticOre extends SWGSiliclasticOre {

  private static final long serialVersionUID = 5100027L;

  private static final int[] minStats = {0, 615, 316, 0, 0, 615, 615, 1, 0, 271, 316};
  private static final int[] maxStats = {0, 802, 502, 0, 0, 802, 802, 1000, 0, 430, 502};

  private static final SWGMalabSiliclasticOre INSTANCE = new SWGMalabSiliclasticOre();

  SWGMalabSiliclasticOre() { super(); }

  public static SWGMalabSiliclasticOre getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 739; }
  public int rcID() { return 644; }
  public String rcName() { return "Malab Siliclastic Ore";}
  public String rcToken() { return "masil";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
