package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Mustafarian Intrusive Ore"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGMustafarianIntrusiveOre extends SWGIntrusiveOre {

  private static final long serialVersionUID = 4902352L;

  private static final int[] minStats = {0, 884, 899, 0, 0, 957, 550, 500, 0, 928, 913};
  private static final int[] maxStats = {0, 1000, 1000, 0, 0, 1000, 600, 1000, 0, 1000, 1000};

  private static final SWGMustafarianIntrusiveOre INSTANCE = new SWGMustafarianIntrusiveOre();

  SWGMustafarianIntrusiveOre() { super(); }

  public static SWGMustafarianIntrusiveOre getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 721; }
  public int rcID() { return 619; }
  public String rcName() { return "Mustafarian Intrusive Ore";}
  public String rcToken() { return "muint";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
