package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGKnownRadioactive;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Mustafarian Radioactive"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGMustafarianRadioactive extends SWGKnownRadioactive {

  private static final long serialVersionUID = 4926073L;

  private static final int[] minStats = {0, 0, 900, 0, 0, 0, 0, 500, 907, 0, 0};
  private static final int[] maxStats = {0, 0, 1000, 0, 0, 0, 0, 1000, 1000, 0, 0};

  private static final SWGMustafarianRadioactive INSTANCE = new SWGMustafarianRadioactive();

  SWGMustafarianRadioactive() { super(); }

  public static SWGMustafarianRadioactive getInstance() { return INSTANCE; }

  public int expectedStats() { return 3; }
  public int sortIndex() { return 637; }
  public int rcID() { return 622; }
  public String rcName() { return "Mustafarian Radioactive";}
  public String rcToken() { return "mukrd";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
