package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Oridium Intrusive Ore"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGOridiumIntrusiveOre extends SWGIntrusiveOre {

  private static final long serialVersionUID = 5558633L;

  private static final int[] minStats = {0, 529, 588, 0, 0, 823, 247, 1, 0, 706, 647};
  private static final int[] maxStats = {0, 671, 712, 0, 0, 877, 354, 1000, 0, 794, 753};

  private static final SWGOridiumIntrusiveOre INSTANCE = new SWGOridiumIntrusiveOre();

  SWGOridiumIntrusiveOre() { super(); }

  public static SWGOridiumIntrusiveOre getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 716; }
  public int rcID() { return 702; }
  public String rcName() { return "Oridium Intrusive Ore";}
  public String rcToken() { return "orint";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
