package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Pholokite Extrusive Ore"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGPholokiteExtrusiveOre extends SWGExtrusiveOre {

  private static final long serialVersionUID = 2032111L;

  private static final int[] minStats = {0, 736, 769, 0, 0, 802, 402, 1, 0, 802, 802};
  private static final int[] maxStats = {0, 864, 881, 0, 0, 898, 498, 1000, 0, 898, 898};

  private static final SWGPholokiteExtrusiveOre INSTANCE = new SWGPholokiteExtrusiveOre();

  SWGPholokiteExtrusiveOre() { super(); }

  public static SWGPholokiteExtrusiveOre getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 707; }
  public int rcID() { return 256; }
  public String rcName() { return "Pholokite Extrusive Ore";}
  public String rcToken() { return "phext";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
