package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Petrochemical Asteroid"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGPetrochemicalAsteroid extends SWGAsteroidalChemical {

  private static final long serialVersionUID = 6056774L;

  private static final int[] minStats = {0, 0, 0, 0, 0, 0, 0, 500, 0, 0, 0};
  private static final int[] maxStats = {0, 0, 0, 0, 0, 0, 0, 500, 0, 0, 0};

  private static final SWGPetrochemicalAsteroid INSTANCE = new SWGPetrochemicalAsteroid();

  SWGPetrochemicalAsteroid() { super(); }

  public static SWGPetrochemicalAsteroid getInstance() { return INSTANCE; }

  public int expectedStats() { return 1; }
  public int sortIndex() { return 803; }
  public int rcID() { return 765; }
  public String rcName() { return "Petrochemical Asteroid";}
  public String rcToken() { return "apet";}
  public boolean isSpaceOrRecycled()  { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
