package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Quadrenium Extrusive Ore"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGQuadreniumExtrusiveOre extends SWGExtrusiveOre {

  private static final long serialVersionUID = 2040018L;

  private static final int[] minStats = {0, 816, 839, 0, 0, 862, 462, 1, 0, 862, 862};
  private static final int[] maxStats = {0, 944, 951, 0, 0, 958, 558, 1000, 0, 958, 958};

  private static final SWGQuadreniumExtrusiveOre INSTANCE = new SWGQuadreniumExtrusiveOre();

  SWGQuadreniumExtrusiveOre() { super(); }

  public static SWGQuadreniumExtrusiveOre getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 708; }
  public int rcID() { return 257; }
  public String rcName() { return "Quadrenium Extrusive Ore";}
  public String rcToken() { return "quext";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
