package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Siliclastic Ore"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public class SWGSiliclasticOre extends SWGSedimentaryOre {

  private static final long serialVersionUID = 1265132L;

  private static final int[] minStats = {0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1};
  private static final int[] maxStats = {0, 1000, 700, 0, 0, 1000, 1000, 1000, 0, 600, 700};

  private static final SWGSiliclasticOre INSTANCE = new SWGSiliclasticOre();

  SWGSiliclasticOre() { super(); }

  public static SWGSiliclasticOre getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 734; }
  public int rcID() { return 159; }
  public String rcName() { return "Siliclastic Ore";}
  public String rcToken() { return "sil";}
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
