package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGSiliclasticOre;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Tertian Siliclastic Ore"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGTertianSiliclasticOre extends SWGSiliclasticOre {

  private static final long serialVersionUID = 5107934L;

  private static final int[] minStats = {0, 848, 549, 0, 0, 848, 848, 1, 0, 470, 549};
  private static final int[] maxStats = {0, 1000, 700, 0, 0, 1000, 1000, 1000, 0, 600, 700};

  private static final SWGTertianSiliclasticOre INSTANCE = new SWGTertianSiliclasticOre();

  SWGTertianSiliclasticOre() { super(); }

  public static SWGTertianSiliclasticOre getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 742; }
  public int rcID() { return 645; }
  public String rcName() { return "Tertian Siliclastic Ore";}
  public String rcToken() { return "tesil";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
