package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGSedimentaryOre;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Unknown Sedimentary Ore"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGUnknownSedimentaryOre extends SWGSedimentaryOre {

  private static final long serialVersionUID = 5645610L;

  private static final int[] minStats = {0, 300, 1, 0, 0, 300, 300, 1, 0, 1, 1};
  private static final int[] maxStats = {0, 1000, 700, 0, 0, 1000, 1000, 1000, 0, 700, 1000};

  private static final SWGUnknownSedimentaryOre INSTANCE = new SWGUnknownSedimentaryOre();

  SWGUnknownSedimentaryOre() { super(); }

  public static SWGUnknownSedimentaryOre getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 724; }
  public int rcID() { return 713; }
  public String rcName() { return "Unknown Sedimentary Ore";}
  public String rcToken() { return "usd";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
