package swg.crafting.resources.types;

import swg.crafting.resources.SWGResourceClass;
import swg.crafting.resources.types.SWGInorganic;
import swg.crafting.Stat;

/*
 * Represents a resource class of type "Water"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public class SWGWater extends SWGInorganic {

  private static final long serialVersionUID = 79082L;

  private static final int[] minStats = {0, 0, 1, 0, 0, 0, 0, 200, 0, 0, 0};
  private static final int[] maxStats = {0, 0, 1000, 0, 0, 0, 0, 1000, 0, 0, 0};

  private static final SWGWater INSTANCE = new SWGWater();

  SWGWater() { super(); }

  public static SWGWater getInstance() { return INSTANCE; }

  public int expectedStats() { return 2; }
  public int sortIndex() { return 599; }
  public int rcID() { return 9; }
  public String rcName() { return "Water";}
  public String rcToken() { return "wtr";}
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
