package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Beyrllius Copper"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGBeyrlliusCopper extends SWGCopper {

  private static final long serialVersionUID = 2348391L;

  private static final int[] minStats = {594, 152, 133, 0, 0, 285, 594, 1, 0, 394, 394};
  private static final int[] maxStats = {683, 294, 257, 0, 0, 365, 683, 1000, 0, 483, 483};

  private static final SWGBeyrlliusCopper INSTANCE = new SWGBeyrlliusCopper();

  SWGBeyrlliusCopper() { super(); }

  public static SWGBeyrlliusCopper getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 686; }
  public int rcID() { return 296; }
  public String rcName() { return "Beyrllius Copper";}
  public String rcToken() { return "becpr";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
