package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Corthel Inert Gas"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGCorthelInertGas extends SWGKnownInertGas {

  private static final long serialVersionUID = 980480L;

  private static final int[] minStats = {0, 0, 167, 0, 0, 0, 0, 1, 0, 0, 0};
  private static final int[] maxStats = {0, 0, 265, 0, 0, 0, 0, 1000, 0, 0, 0};

  private static final SWGCorthelInertGas INSTANCE = new SWGCorthelInertGas();

  SWGCorthelInertGas() { super(); }

  public static SWGCorthelInertGas getInstance() { return INSTANCE; }

  public int expectedStats() { return 2; }
  public int sortIndex() { return 789; }
  public int rcID() { return 123; }
  public String rcName() { return "Corthel Inert Gas";}
  public String rcToken() { return "cokrt";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
