package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Carbonite Steel"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGCarboniteSteel extends SWGSteel {

  private static final long serialVersionUID = 2206065L;

  private static final int[] minStats = {501, 616, 885, 0, 0, 908, 308, 1, 0, 885, 862};
  private static final int[] maxStats = {605, 744, 965, 0, 0, 972, 372, 1000, 0, 965, 958};

  private static final SWGCarboniteSteel INSTANCE = new SWGCarboniteSteel();

  SWGCarboniteSteel() { super(); }

  public static SWGCarboniteSteel getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 653; }
  public int rcID() { return 278; }
  public String rcName() { return "Carbonite Steel";}
  public String rcToken() { return "cbstl";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
