package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Frasium Carbonate Ore"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGFrasiumCarbonateOre extends SWGCarbonateOre {

  private static final long serialVersionUID = 5566540L;

  private static final int[] minStats = {0, 536, 237, 0, 0, 603, 536, 1, 0, 237, 470};
  private static final int[] maxStats = {0, 676, 377, 0, 0, 723, 676, 1000, 0, 377, 630};

  private static final SWGFrasiumCarbonateOre INSTANCE = new SWGFrasiumCarbonateOre();

  SWGFrasiumCarbonateOre() { super(); }

  public static SWGFrasiumCarbonateOre getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 729; }
  public int rcID() { return 703; }
  public String rcName() { return "Frasium Carbonate Ore";}
  public String rcToken() { return "frcrb";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
