package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Hollinium Intrusive Ore"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGHolliniumIntrusiveOre extends SWGIntrusiveOre {

  private static final long serialVersionUID = 5542819L;

  private static final int[] minStats = {0, 707, 743, 0, 0, 890, 380, 1, 0, 817, 780};
  private static final int[] maxStats = {0, 849, 868, 0, 0, 943, 487, 1000, 0, 906, 887};

  private static final SWGHolliniumIntrusiveOre INSTANCE = new SWGHolliniumIntrusiveOre();

  SWGHolliniumIntrusiveOre() { super(); }

  public static SWGHolliniumIntrusiveOre getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 718; }
  public int rcID() { return 700; }
  public String rcName() { return "Hollinium Intrusive Ore";}
  public String rcToken() { return "hoint";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
