package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Low Quality Gemstone"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGLowQualityGemstone extends SWGGemstone {

  private static final long serialVersionUID = 6491659L;

  private static final int[] minStats = {0, 200, 200, 200, 0, 200, 200, 200, 0, 200, 200};
  private static final int[] maxStats = {0, 200, 200, 200, 0, 200, 200, 200, 0, 200, 200};

  private static final SWGLowQualityGemstone INSTANCE = new SWGLowQualityGemstone();

  SWGLowQualityGemstone() { super(); }

  public static SWGLowQualityGemstone getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 744; }
  public int rcID() { return 820; }
  public String rcName() { return "Low Quality Gemstone";}
  public String rcToken() { return "lgem";}
  public boolean isSpaceOrRecycled()  { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
