package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Low Grade Ore (Siliclastic)"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGLowGradeOreSiliclastic extends SWGSiliclasticOre {

  private static final long serialVersionUID = 6507473L;

  private static final int[] minStats = {0, 200, 200, 0, 0, 200, 200, 200, 0, 200, 200};
  private static final int[] maxStats = {0, 200, 200, 0, 0, 200, 200, 200, 0, 200, 200};

  private static final SWGLowGradeOreSiliclastic INSTANCE = new SWGLowGradeOreSiliclastic();

  SWGLowGradeOreSiliclastic() { super(); }

  public static SWGLowGradeOreSiliclastic getInstance() { return INSTANCE; }

  public int expectedStats() { return 7; }
  public int sortIndex() { return 735; }
  public int rcID() { return 822; }
  public String rcName() { return "Low Grade Ore (Siliclastic)";}
  public String rcToken() { return "lsil";}
  public boolean isSpaceOrRecycled()  { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
