package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Mustafarian Solid Petro Fuel"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGMustafarianSolidPetroFuel extends SWGKnownSolidPetrochemFuel {

  private static final long serialVersionUID = 4791654L;

  private static final int[] minStats = {0, 0, 750, 0, 0, 0, 0, 500, 870, 0, 0};
  private static final int[] maxStats = {0, 0, 800, 0, 0, 0, 0, 1000, 1000, 0, 0};

  private static final SWGMustafarianSolidPetroFuel INSTANCE = new SWGMustafarianSolidPetroFuel();

  SWGMustafarianSolidPetroFuel() { super(); }

  public static SWGMustafarianSolidPetroFuel getInstance() { return INSTANCE; }

  public int expectedStats() { return 3; }
  public int sortIndex() { return 625; }
  public int rcID() { return 605; }
  public String rcName() { return "Mustafarian Solid Petro Fuel";}
  public String rcToken() { return "muksp";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
