package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Mustafarian Type 1 Crystal Amorphous Gem"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGMustafarianType1CrystalAmorphousGem extends SWGAmorphousGemstone {

  private static final long serialVersionUID = 4949794L;

  private static final int[] minStats = {0, 870, 870, 750, 0, 948, 550, 1, 0, 870, 870};
  private static final int[] maxStats = {0, 1000, 1000, 800, 0, 1000, 600, 1000, 0, 1000, 1000};

  private static final SWGMustafarianType1CrystalAmorphousGem INSTANCE = new SWGMustafarianType1CrystalAmorphousGem();

  SWGMustafarianType1CrystalAmorphousGem() { super(); }

  public static SWGMustafarianType1CrystalAmorphousGem getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 757; }
  public int rcID() { return 625; }
  public String rcName() { return "Mustafarian Type 1 Crystal Amorphous Gem";}
  public String rcToken() { return "m1amo";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
