package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Polonium Iron"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGPoloniumIron extends SWGIron {

  private static final long serialVersionUID = 2190251L;

  private static final int[] minStats = {45, 71, 361, 0, 0, 544, 53, 1, 0, 453, 453};
  private static final int[] maxStats = {144, 231, 501, 0, 0, 644, 173, 1000, 0, 573, 573};

  private static final SWGPoloniumIron INSTANCE = new SWGPoloniumIron();

  SWGPoloniumIron() { super(); }

  public static SWGPoloniumIron getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 661; }
  public int rcID() { return 276; }
  public String rcName() { return "Polonium Iron";}
  public String rcToken() { return "poirn";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
