package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Rudic Amorphous Gemstone"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGRudicAmorphousGemstone extends SWGAmorphousGemstone {

  private static final long serialVersionUID = 1146527L;

  private static final int[] minStats = {0, 371, 371, 297, 0, 748, 223, 1, 0, 371, 371};
  private static final int[] maxStats = {0, 530, 530, 424, 0, 812, 318, 1000, 0, 530, 530};

  private static final SWGRudicAmorphousGemstone INSTANCE = new SWGRudicAmorphousGemstone();

  SWGRudicAmorphousGemstone() { super(); }

  public static SWGRudicAmorphousGemstone getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 751; }
  public int rcID() { return 144; }
  public String rcName() { return "Rudic Amorphous Gemstone";}
  public String rcToken() { return "ruamo";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
