package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Ryll Amorphous Gemstone"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGRyllAmorphousGemstone extends SWGAmorphousGemstone {

  private static final long serialVersionUID = 1154434L;

  private static final int[] minStats = {0, 471, 471, 377, 0, 788, 283, 1, 0, 471, 471};
  private static final int[] maxStats = {0, 630, 630, 504, 0, 852, 378, 1000, 0, 630, 630};

  private static final SWGRyllAmorphousGemstone INSTANCE = new SWGRyllAmorphousGemstone();

  SWGRyllAmorphousGemstone() { super(); }

  public static SWGRyllAmorphousGemstone getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 752; }
  public int rcID() { return 145; }
  public String rcName() { return "Ryll Amorphous Gemstone";}
  public String rcToken() { return "ryamo";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
