package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Regvis Amorphous Gemstone"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGRegvisAmorphousGemstone extends SWGAmorphousGemstone {

  private static final long serialVersionUID = 5139562L;

  private static final int[] minStats = {0, 171, 171, 137, 0, 668, 103, 1, 0, 171, 171};
  private static final int[] maxStats = {0, 331, 331, 265, 0, 732, 199, 1000, 0, 331, 331};

  private static final SWGRegvisAmorphousGemstone INSTANCE = new SWGRegvisAmorphousGemstone();

  SWGRegvisAmorphousGemstone() { super(); }

  public static SWGRegvisAmorphousGemstone getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 749; }
  public int rcID() { return 649; }
  public String rcName() { return "Regvis Amorphous Gemstone";}
  public String rcToken() { return "reamo";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
