package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Rhodium Steel"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGRhodiumSteel extends SWGSteel {

  private static final long serialVersionUID = 2277228L;

  private static final int[] minStats = {1, 1, 500, 0, 0, 600, 1, 1, 0, 500, 400};
  private static final int[] maxStats = {85, 105, 565, 0, 0, 652, 53, 1000, 0, 565, 478};

  private static final SWGRhodiumSteel INSTANCE = new SWGRhodiumSteel();

  SWGRhodiumSteel() { super(); }

  public static SWGRhodiumSteel getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 645; }
  public int rcID() { return 287; }
  public String rcName() { return "Rhodium Steel";}
  public String rcToken() { return "rhstl";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
