package swg.crafting.resources.types;

import swg.crafting.Stat;

/*
 * Represents a resource class of type "Vendusii Crystal Amorphous Gemstone"
 *
 * <b>WARNING:</b>
 * This class is generated by SWGResourceClassGenerator.
 * Do not manually modify this class as your changes are
 * erased when the classes are re-generated.
 *
 * @author Steven M. Doyle <shadow@triwizard.net>
 * @author <a href="mailto:simongronlund@gmail.com">Simon Gronlund</a>
 * aka Chimaera.Zimoon
 */
@SuppressWarnings("all")
public final class SWGVendusiiCrystalAmorphousGemstone extends SWGAmorphousGemstone {

  private static final long serialVersionUID = 1170248L;

  private static final int[] minStats = {0, 770, 770, 616, 0, 908, 462, 1, 0, 770, 770};
  private static final int[] maxStats = {0, 930, 930, 744, 0, 972, 558, 1000, 0, 930, 930};

  private static final SWGVendusiiCrystalAmorphousGemstone INSTANCE = new SWGVendusiiCrystalAmorphousGemstone();

  SWGVendusiiCrystalAmorphousGemstone() { super(); }

  public static SWGVendusiiCrystalAmorphousGemstone getInstance() { return INSTANCE; }

  public int expectedStats() { return 8; }
  public int sortIndex() { return 755; }
  public int rcID() { return 147; }
  public String rcName() { return "Vendusii Crystal Amorphous Gemstone";}
  public String rcToken() { return "veamo";}
  public boolean isSpawnable() { return true; }
  public boolean has(Stat s) { return minStats[s.i] > 0; }
  public int max(Stat s) { return maxStats[s.i]; }
  public int min(Stat s) { return minStats[s.i]; }

  private Object readResolve() {
    return INSTANCE; // preserve singleton property
  }
}
